### ISSUE TITLE
Large Resolutions

### ISSUE THREAD

**Issue by DanielArnett** [andreacremaschi/Syphon-virtual-screen#26]
When setting the screen resolution to something greater than 1024x1024 (e.g. 1024x1064) both the real and virtual screens will become unusable and the computer will need to be restarted.

**Comment by andreacremaschi** [comment]
Double check your EWProxyFrameBuffer.kext/Contents/Info.plist: you probably haven't changed the "MaxResolution" section to cope with your new maximum resolution. This is important because these values set the size of the buffer that is being allocated on startup, the one that emulates the fake video frame buffer.
